### ISSUE TITLE
key binding

### ISSUE THREAD

**Issue by yannfill** [ymatsiuk/nixos-config#3]
Hi,

Did you managed to bind PageUp/PageDown to RightCTRL+Up/Down on 9310?

I tried in sway an alacritty config files but can't make it work.

**Comment by ymatsiuk** [comment]
I don't use these keys :shrug: 
You could get the key codes using `wev` (`nix run nixpkgs#wev` if you're on NixOS) and use something like [ydtool](https://github.com/ReimuNotMoe/ydotool) to send `ydotool key pageup`.
Good Luck!
